footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.1
resolution: 0.4
robot_base_frame: base_link
obstacle_range: 20.0
raytrace_range: 21.0
transform_tolerance: 2.0


recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}]

obstacle_layer:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}
#obstacle_layer:
#   observation_sources: scan
#   scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}

inflation_layer:
   inflation_radius: 4.0
   cost_scaling_factor: 0.5
