global_frame: odom
rolling_window: true
track_unknown_space: true
footprint_padding: 0.8
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
