global_frame: odom
robot_base_frame: base_link
rolling_window: true
width: 20
height: 20
plugins:
  - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
