global_frame: map
static_map: true
rolling_window: false
track_unknown_space: true
width: 2000.0
height: 2000.0
plugins:
  - {name: static_layer,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_layer,               type: "costmap_2d::InflationLayer"}

