asc:
 asc_state_controller:
   type: "joint_state_controller/JointStateController"
   publish_rate: 50  
 left_front_steering_joint:
   type: position_controllers/JointPositionController
   joint: left_front_steering_joint
   pid: {p: 1000000.0, i: 0.01, d: 10.0}
 right_front_steering_joint:
   type: position_controllers/JointPositionController
   joint: right_front_steering_joint
   pid: {p: 1000000.0, i: 0.01, d: 10.0}
 four_wheel_steering_controller:
   type: "four_wheel_carlike_steering_controller/FourWheelCarlikeSteeringController"
   front_wheel: ['left_front_wheel_joint', 'right_front_wheel_joint']
   rear_wheel: ['left_rear_wheel_joint', 'right_rear_wheel_joint']
   front_steering: ['left_front_steering_joint', 'right_front_steering_joint']
   rear_steering: ['left_rear_steering_joint', 'right_rear_steering_joint']
   publish_rate: 50
   pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
   twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
   cmd_vel_timeout: 25.0 # not tested here
 
   # Base frame_id
   base_frame_id: frame_link
 
   # Odometry fused with IMU is published by robot_localization, so
   # no need to publish a TF based on encoders alone.
   enable_odom_tf: true
 

