gazebo_ros_control/pid_gains:
  front_left_steering_joint: {p: 50.0, i: 5.0, d: 5.0}
  front_right_steering_joint: {p: 50.0, i: 5.0, d: 5.0}
  rear_left_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
  rear_right_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
  front_left_wheel_joint: {p: 0.0, i: 0.0, d: 0.0}  
  front_right_wheel_joint: {p: 0.0, i: 0.0, d: 0.0}  
  rear_left_wheel_joint: {p: 10.0, i: 0.0, d: 0.0}  
  rear_right_wheel_joint: {p: 10.0, i: 0.0, d: 0.0}  


#left_rear_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#right_rear_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#left_front_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
#right_front_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
#left_front_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}  
#right_front_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#rear_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#front_steer_joint: {p: 1.0, i: 0.0, d: 1.0}    
