gazebo_ros_control/pid_gains:
  left_front_steering_joint: {p: 50.0, i: 5.0, d: 5.0}
  right_front_steering_joint: {p: 50.0, i: 5.0, d: 5.0}
  left_rear_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
  right_rear_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
  left_front_wheel_joint: {p: 0.0, i: 0.0, d: 0.0}  
  right_front_wheel_joint: {p: 0.0, i: 0.0, d: 0.0}  
  left_rear_wheel_joint: {p: 10.0, i: 0.0, d: 0.0}  
  right_rear_wheel_joint: {p: 10.0, i: 0.0, d: 0.0}  


#left_rear_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#right_rear_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#left_front_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
#right_front_steering_joint: {p: 1.0, i: 0.0, d: 1.0}
#left_front_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}  
#right_front_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#rear_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
#front_steer_joint: {p: 1.0, i: 0.0, d: 1.0}    
